# Generated by Django 5.0.7 on 2024-07-16 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_admin_inventory_products_seller_transaction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='description',
        ),
        migrations.RemoveField(
            model_name='products',
            name='short_description',
        ),
    ]
