# Generated by Django 5.0.7 on 2024-07-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_products_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='short_description',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
