# Generated by Django 5.1 on 2024-08-08 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_products_description_products_short_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='order_details',
            new_name='OrderDetails',
        ),
    ]
